### ISSUE TITLE
Need for clarification in the "Mathematical Foundation" section of documentation

### ISSUE THREAD

**Issue by bpstahlman** [parinfer/parinfer.js#115]
I believe I have an intuitive understanding of which open parens correspond to
sn[-p] and sn[-p-1], but the indexing seems wrong to me. (Perhaps I just
misunderstand the notation; hence, the need for clarification...)

Here's a 3 line example to make things concrete:

```
(a
  ( (b)
   c))
```

For n=3...

```
t3 = ['c', ')', ')']
i3 = 3
p3 = 2
s3 = [
    <x-pos-of-open-paren-on-line-1>,
    <x-pos-of-first-open-paren-on-line-2>
]
```

Note: I didn't add the second open-paren on line 2 to s3[] because it is
closed before t3[-p3]. (At least I think it is, but maybe I've misunderstood
what is meant by "before tn[-pn]".)

I'm assuming that negative indices count from the end of the array/stack, but
if that's the case, then s3[-p3] would correspond to the "parent list" paren
(on line 1), and s3[-p3-1] wouldn't even exist, so clearly, either my
assumption about the meaning of negative indices, or my understanding of the
nature of s3[] is flawed.

Actually, it occurred to me that if we ignore end of line parens, s3[] would
also contain the second open-paren on line 2. This would make sense, since
'(b) in this case would qualify as a "previous sibling", and is indeed what
should determine xmax for line 3. But even if I were to add...

```
    <x-pos-of-second-open-paren-on-line-2>
```

...to the end of s3[], I don't see how -p3 would be the correct index. (Looks
as though it would be -1, with the "parent list" open-paren at index -2.)

What am I missing here? Either 1) there's a mistake in the docs, 2) I've
misunderstood what goes in sn[], or 3) I've misunderstood the indexing
notation, or 4) ???

**Comment by shaunlebron** [comment]
Glad someone's checking my math.  Thanks!

Something to look out for is the subscript indexes in the actual invariant:

<img width="196" alt="screen shot 2016-08-12 at 12 10 39 am" src="https://cloud.githubusercontent.com/assets/116838/17615176/407b3eba-6021-11e6-9f2e-2126431bf024.png">

You got nothing wrong in your example!  Your only confusion was this: i3 has a significant relationship to p2 and s2, not p3 and s3.

As for what to do when s3[-p3-1] doesn't exist, that expression is only evaluated if the stack size `|s| > p`.  Otherwise we use -1.

<img width="254" alt="screen shot 2016-08-12 at 12 21 03 am" src="https://cloud.githubusercontent.com/assets/116838/17615599/330347ca-6024-11e6-8aae-750db4cdf349.png">

Happy to clarify if needed

**Comment by bpstahlman** [comment]
Ah! I was so focused on the other equations, I didn't even notice the n vs n-1 distinction in the invariant! I'll go over a few more examples to be sure I've got it when I have time later, but I think that clears it up for me. Thanks for the clarification!

**Comment by shaunlebron** [comment]
thanks again for checking!
