### ISSUE TITLE
Multi Arity functions in Indent mode

### ISSUE THREAD

**Issue by ashercoren** [parinfer/parinfer.js#118]
When writing a multi arity functions, the regular way of writing it is:

``` clojure
(def f
  ([a]
    (+ a 3))
  ([a b]
    (+ a b)))
```

Where each arity option has a list of parameters, followed by the function implementation. The function implementation is indented one level further than the list of parameters.

With indent mode, this automatically gets changed, since the function implementation is nested inside the variable list, so it gets changed to:

``` clojure
(def f
  ([a
    (+ a 3)])
  ([a b
    (+ a b)]))
```

**Comment by shaunlebron** [comment]
Thanks for reporting!  This is a known issue, and is the only irreconcilable inconsistency with the clojure indentation standards.  When designing parinfer, I ran it against all clojure core repos to be sure that this was the only thing that had to go.

If it's any consolation, Parinfer is actually still compatible with the Clojure Style Guide, since it has a strict stance [against indenting multi-arities that way](https://github.com/bbatsov/clojure-style-guide#multiple-arity-indentation).  I brought up how this contradicts real-world usage to the style guide author [here](https://github.com/bbatsov/clojure-style-guide/pull/95#issuecomment-148740902).  You can read his response there.

So, from the perspectives of everyone involved:
- Users want it because it helps readability by separating arities from the bodies.
- I can't fix it because it would make my automation rules inconsistent.
- The style guide author doesn't like it because it's inconsistent with how single-arity functions are written.

**Comment by facundoolano** [comment]
I use the same indentation suggested in the style guide you mentioned. I always run into problems, though, when converting a function of single arity into a multiple arity one. I can't seem to find a way to wrap the old body around a new set of parenthesis without breaking the code:

``` clj
(defn foo
  "What I have."
  [x]
  (bar x))

(defn foo
  "What I'd like next (before adding the other arity definition)."
  ([x]
   (bar x)))

(defn foo
  "What I actually get."
  ([x
    (bar x)]))
```

I can't tell if it's parinfer or the editor -sublime- causing it. If it's parinfer, I wonder if that's a behaviour that could be changed.

**Comment by facundoolano** [comment]
Actually, nevermind, I just noticed I can avoid that by changing to `paren` mode before adding the new parentheses.

**Comment by shaunlebron** [comment]
@facundoolano yeah, it's a common enough hiccup.  still thinking on alternate resolutions
