### ISSUE TITLE
Inline paren inference

### ISSUE THREAD

**Issue by shaunlebron** [parinfer/parinfer.js#141]
Try https://github.com/shaunlebron/parinfer/issues/131 again but with extra context provided by the `changes` option

What do I mean by "inline"?  Well, Parinfer was started by having close-parens inferred from _indentation_.  But indentation does not help us infer anything in something like:

```clj
((foo (bar) baz) bat)
```

So when we modify it by adding a `[`, for example:

```
((foo (bar[) baz) bat)
          +
```

Perhaps we would expect this:

```
((foo (bar[]) baz) bat)
```

Or if we add a `)`, for example:

```
((foo (bar)) baz) bat)
           +
```

Perhaps we would expect this to mean that we are moving the close-paren from `baz)` back:

```
((foo (bar)) baz bat)
```

[Paredit emerged] without hotkeys for cases when indentation allowed inference.  Perhaps new rules can bridge the gap such that they apply for inline cases.  We have the `changes` information to try now.

[Paredit emerged]:http://shaunlebron.github.io/parinfer/#paredit-emerges

**Comment by CmdrDats** [comment]
I'm aware that I don't have the full scale of things in my head, since I'm not the one implementing this - but I'd like to share what I'd expect to see in the various cases and what rules my head would use, at least as a datapoint to consider.

I'll use the word 'paren' to match brace, bracket or curly - `[{(`

Case 1:
```
(foo (bar [) baz) bat)
          +
=> (foo (bar []) baz) bat)
```
Opening paren, search left for symbols - terminate and insert closing paren if another closing paren is found at same level (ie, skip over any new forms):

```
(foo (bar [ car (cat)) baz) bat)
          +
=> (foo (bar [ car (cat)]) baz) bat)
```

Similarly, when inserting closing paren, look form-wise forward for a _matching_ paren terminating the current level, and pull it back - if not found, insert matching paren at cursor such that cursor in between parens:

```
(foo (bar ]) baz) bat)
          +
=> (foo (bar [|]) baz) bat)
```

And with the pre-existing terminator:
```
(foo (let [x] (bar) y]) baz) bat)
            +
=> (foo (let [x] (bar) y) baz) bat)

```

Removing a paren just finds the matching level closing paren and remove that too - Since structural integrity is basically being enforced, there shouldn't be cases where they are straggling? if there are, I guess you default to doing nothing else.

Of course - all of this is probably wildly at odds with indentation based logic - but perhaps there's a way to deal with paren insertion/removal at a local scope first, and then run the indentation logic afterward?

Hopefully this is helpful! I'm keen to hear more about cases where the above logic breaks - I'm quite sure there's plenty I haven't considered, but would like to learn more.

**Comment by shaunlebron** [comment]
For maintenance, I really just think it’s best to not do anything, and allow unmatched parens to be corrected manually (with `forceBalance` off).  I think it’s a good balance to have Parinfer handle the big indentation-based cases, and to have a person handle the inline ones depending on what they want— which only seems predictable some of the time.
