### ISSUE TITLE
Parlinter is archived, what to use instead?

### ISSUE THREAD

**Issue by devurandom** [parinfer/parinfer.js#210]
I saw that https://github.com/parinfer/parlinter is archived, but there is no indication in the readme or GH issues what to use instead. https://github.com/parinfer/parinfer.js#a-stable-core-for-editor-plugins also still suggests the use of parlinter, not recognizing that it is archived. What linter should I use instead of parlinter?

**Comment by shaunlebron** [comment]
I’m not confident that parlinter was a useful thing, so I archived it.  You can still use it, it’ll work.

**Comment by gilch** [comment]
I still use it, both [in my Hissp project](https://github.com/gilch/hissp/blob/master/.github/workflows/test-package.yml#L38) and in our Clojure pipeline at work.

**Comment by shaunlebron** [comment]
> I still use it, both [in my Hissp project](https://github.com/gilch/hissp/blob/master/.github/workflows/test-package.yml#L38) and in our Clojure pipeline at work.

@gilch hey thanks for letting me know!  do you work with other clojure devs who don’t use parinfer?

**Comment by gilch** [comment]
Yes, most of them are using Parinfer now because they're using my Spacemacs config, although we have one holdout insisting on IntelliJ. But I introduced them to it, and at the time many files in our codebase weren't compliant. I used Parlinter to find them and added it to the pipeline to keep them that way. We still occasionally edit files in Vim (usually when resolving merge conflicts) or in the GitHub webUI, neither of which have Parinfer installed, so the pipeline check still prevents accidents. It's just one of many linters in our process.

I don't know of a way to add Parinfer to the web editor, and even if I could, that doesn't necessarily mean everyone would use it. I probably could add it to Vim, but Parinfer chokes on merge conflict files, so it's easier to leave it off. It would be nice if Parinfer could automatically turn itself off when it detects the lines that git adds. Many editors will automatically reload a buffer when they detect an external change to the file, then Parinfer will promptly corrupt it.
