### ISSUE TITLE
Consider combining Paren and Indent into a single mode

### ISSUE THREAD

**Issue by jasongilman** [parinfer/parinfer.js#86]
I've been using Parinfer since it came out for Atom. I find it very useful but I struggle with remembering to switch between Indent and Paren mode. I edit mostly in Indent mode and then switch to Paren after messing up my parentheses when changing an identifier or commenting out a form with `#_`. I'm not sure if it's possible or even makes sense but it seems like you could combine them into two modes. It seems like all of the cases shown for [Paren Mode](https://shaunlebron.github.io/parinfer/#paren-mode) could be inferred given the context of the modification. For example adding non-whitespace characters onto an identifier before a multiline form should apply changes as in paren mode.

You might be able to determine the mode to use based on the kind of change:
- Addition of whitespace (newlines, tabs, spaces): indent mode.
- Removal of lines, commenting out lines: indent mode
- Addition or removal of parens: indent mode
- Addition or removal of any other normal character: paren mode

**Comment by shaunlebron** [comment]
I really like the idea of exploring this. :+1:  Thanks

The biggest hurdle for this "Auto" mode will be creating the heuristics for choosing the appropriate mode based on the type of change, as you've described.  I'm worried about how to predict all the implications of the changes you described with such heuristics, and whether they will be predictable by the user or not.  It might just require some diligence and exhaustive test cases to see though.

For example, if I follow your suggested heuristics after inserting a `[` before `(foo` in the code:

``` clj
(foo
 bar)
```

then I get this:

``` clj
[(foo)
 bar]
```

I'm not sure if the user would've expected this instead:

``` clj
[(foo
  bar)]
```

It might be best to start by basing an initial heuristic on a very limited scope of changes, see how that feels, then keep increasing scope:
- if a single space is inserted into a line's indentation region: indent mode
- else if some other character was inserted: paren mode
- else: default mode

Then we can start increasing the scope to consider the following types of changes:
- deleting single characters
- replacing some selection inside a line
- deleting a `\n` character (causing two lines to join)
- replacing some selection across multiple lines
- ...

**Comment by cursive-ghost** [comment]
Here are some cases that are seem wrong as a new user (all in indent mode):

```
(let [x 10]<caret>
  (when true))
```

If I press `)` here, the paren is inserted but will be removed as soon as parinfer is run again. When it's inserted it will be held there by the caret clamping, but as soon as you move off that line the paren will be removed and replaced to its original spot. While the caret is being clamped the invariants of the document are not correct (`(when true)` is incorrectly indented).

```
(let<caret> [x 10]
  (when true))
```

If I insert a close paren here, the indentation on the second line is incorrect and is never fixed - the document invariants are broken.

```
(<caret>let [x 10]
  (when true))
```

If I insert an opening paren here, the indentation on the second line is not corrected, which I think it should be.

I'm considering implementing a hybrid mode for Cursive. For change events I have the before and after text. I think that if the paren/brace open/close stack differs between the two, then I will reindent the top level form after running indent mode. I'd have to try it, but I think that's the right semantics.

**Comment by shaunlebron** [comment]
When a `)` is typed, run Paren Mode (solves first two examples).

When a `(` is typed, run Indent Mode as normal (to insert the inferred close-paren).  Then run an auto-indent script that is configured to give a two-space indentation for let-forms (this type of exact config is currently outside the scope of Paren Mode given that it just clamps to indentation thresholds).

**Comment by shaunlebron** [comment]
> ```
> (let<caret> [x 10]
>   (when true))
> ```
>
> If I insert a close paren here, the indentation on the second line is incorrect and is never fixed - the document invariants are broken.

A correction after revisiting-- the resulting code is still fine under the invariant, since we don't enforce alignment of sibling lines.  In other words, indenting to the right of a previous line is fine as long as the previous line is not a parent.  To see this, Paren Mode performs no corrections on the resulting code from your example:

```clj
(let) [x 10]
  (when true)
```

That said, it still doesn't look right. Being aggressive with sibling alignment while editing could feel weird as well.  Will keep thinking about this since it could be related to the upcoming auto-indent feature (i.e. it will auto-indent a new line to match previous sibling line if possible).

**Comment by shaunlebron** [comment]
Also, tracking this update from @doglooksgood on slack about unforeseen difficulty in combining modes:

https://clojurians-log.clojureverse.org/parinfer/2016-11-29.html#inst-2016-11-29T10:53:00.000214Z

**Comment by DogLooksGood** [comment]
Hi, @shaunlebron. Just saw this comment, is there any plan for add a hybrid mode?

**Comment by shaunlebron** [comment]
I've been busy wrapping up the individual modes, but if we want to combine them, here's a plan you guys can help with.

## Plan

1. come up with examples of desired behavior
1. create rules based on these examples
1. see if these rules can generate examples of _undesired_ behavior
1. come up with compromises if step 3 turns up anything

we can work backwards from @jasongilman's rules or @DogLooksGood's rules to create examples:

- [jason's rules](https://github.com/shaunlebron/parinfer/issues/86#issue-128227941)
- [tianshu's rules](https://github.com/DogLooksGood/parinfer-mode/blob/master/HOW_TO_WRAP_SEXP.org#more-ideas)

**Comment by shaunlebron** [comment]
Another reference for creating examples-- the author of the [parinfer critique](https://github.com/noctuid/parinfer-notes) added some [key commands](http://oremacs.com/lispy/parinfer_index.html) to emacs-lispy-plugin to mimic some of parinfer's examples in a single mode.  Bugs discussion happening at https://github.com/abo-abo/lispy/issues/230.

**Comment by rgdelato** [comment]
Hello there! First off, I wanted to say that I'm a relative newcomer to Clojure, so I wanted to say thank you for Parinfer! I can't tell you how much it's helped in getting me up and running with learning a Lisp language.

> ## Plan
> 1. come up with examples of desired behavior

Alright, so here's what I can think of for desired behavior.

### Example 1

First, when I'm changing the last line in an top-level form, I want it to act like Indent Mode:

```clojure
(defn foo
  "hello, this is a docstring"
  [a b]
  (let [sum (+ a b)
        prod (* a b)]
     {:sum sum
      |:prod prod}))
```

If I press delete, I want `:prod prod` to move outside of the hash map, and if I press space afterward, I want it to go back inside of the hash map. This currently works wonderfully in "Indent Mode."

**Desired result of pressing delete:** (works in Indent Mode)

```clojure
(defn foo
  "hello, this is a docstring"
  [a b]
  (let [sum (+ a b)
        prod (* a b)]
     {:sum sum}
     :prod prod))
```

### Example 2

But if I'm in front of a block, I want it to act more like Paren Mode, pushing out the block when more space/characters are added:

```clojure
(defn foo
  "hello, this is a docstring"
  [a b]
  (let |[sum (+ a b)
        prod (* a b)]
     {:sum sum
      :prod prod}))
```

If I press space here, I want a space to be added in front of both `[sum` and `prod (* a b)` so that `prod (* a b)` doesn't fall out of the binding. I currently have to switch to "Paren Mode" to get this behavior.

**Desired result of pressing space:** (works in Paren Mode)

```clojure
(defn foo
  "hello, this is a docstring"
  [a b]
  (let  [sum (+ a b)
         prod (* a b)]
     {:sum sum
      :prod prod}))
```

### Example 3

I don't know if this makes sense, but looking at these two cases, I think that what I actually want for all cases is kind of an "Indent Mode" before the cursor position and "Paren Mode" after the cursor position:

```clojure
(defn foo
  "hello, this is a docstring"
  [a b]
  |(let [sum (+ a b)
        prod (* a b)]
     {:sum sum
      :prod prod}))
```

If I press space here, what I want is for the `let` block to go inside of the function parameters, but for the entire structure within the `let` block to still be maintained so that `prod (* a b)` doesn't fall out of the `let` binding. Neither "Indent Mode" nor "Paren Mode" currently do this.

**Desired result of pressing space:** (neither mode does this)

```clojure
(defn foo
  "hello, this is a docstring"
  [a b
   (let [sum (+ a b)
         prod (* a b)]
      {:sum sum
       :prod prod})])
```

I hope I'm making some kind of sense, and I'm sure that there are a million edge cases that I'm not seeing, but I think the basic idea of happily changing the structure of code above the cursor position and trying to hold code structure below the cursor position might be a decent baseline for how I'd want a "Mixed Mode" to behave?

**Comment by shaunlebron** [comment]
thanks @rgdelato. might finally lead to something!

on mobile on short vacation. will look when i get back


_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shaunlebron** [comment]
@rgdelato this will require a new `change` option that I'm exploring here: https://github.com/shaunlebron/parinfer/issues/138

**Comment by rgdelato** [comment]
@shaunlebron In a way, that's unfortunate to hear, since I had some hope that this kind of mixed mode would still be possible using the current method. But knowing what changed should give you a lot more to work with, so I definitely hope it works out and I'll be following along.

**Comment by shaunlebron** [comment]
@rgdelato 

💡 Actually, maybe your examples just need a `cursorDx` option for indent mode?

(I think my brain skipped to the `change` option since it also applies to other issues I was hoping to solve in one sweep.  I'll try the `cursorDx` thing first)

**Comment by shaunlebron** [comment]
Indent Mode with `cursorDx` seems promising:

- video: https://www.youtube.com/watch?v=9iZfdfsoC5o
- try it here: http://shaunlebron.github.io/parinfer/demo

**Comment by shaunlebron** [comment]
I've been playing with it for a bit in an early version of atom-parinfer, and it seems good!

In summary, this "unified mode" is achieved if you pass a `changes` option to Indent Mode in v3. I imagine Paren Mode is now obsolete.  Closing for now!

**Comment by achikin** [comment]
The demo at http://shaunlebron.github.io/parinfer/demo is broken for me.
```
Uncaught TypeError: Cannot read property 'join' of undefined
    at Vv (parinfer-site.js:2)
    at parinfer-site.js:1
    at G.f.Ha (parinfer-site.js:1)
    at Function.Bb.h (parinfer-site.js:1)
    at eg (parinfer-site.js:1)
    at Yv (parinfer-site.js:2)
    at DC (parinfer-site.js:3)
    at codemirror.js:31
    at fireCallbacksForOps (codemirror.js:16)
    at endOperation (codemirror.js:16)
```

**Comment by shaunlebron** [comment]
@achikin: thanks for letting me know!  was an externs problem, but fixed now.

**Comment by Kurvivor19** [comment]
Sorry for butting in - does that new mode messes structure of an opened
document with "correct parens but wrong indents"?

2017-07-18 10:19 GMT+03:00 Shaun Lebron <notifications@github.com>:

**Comment by shaunlebron** [comment]
you still have to use paren mode to preprocess your file

**Comment by shaunlebron** [comment]
@Kurvivor19 I meant to clarify that Paren Mode may only be obsolete to the user, not for plugins that still need it for preprocessing files.

**Comment by shaunlebron** [comment]
This is now called "Smart Mode" and has its own `smartMode` function.  Demo page now defaults to this mode if you want to try it out while we continue experimenting with it:
http://shaunlebron.github.io/parinfer/demo

**Comment by jasongilman** [comment]
I'm finally giving this a try in the Atom editor and it's amazing. I amazed at how it just does what I want when editing the code. Great work
